export const countiesAndSubCounties = [
  {
    name: 'Nairobi',
    sub_counties: [
      'Westlands',
      "Lang'ata",
      'Starehe',
      'Kasarani',
      'Embakasi',
      'Makadara',
      'Kibra',
      'Roysambu',
      'Dagoretti North',
      'Dagoretti South',
      'Mathare',
      'Ruaraka',
      'Embakasi North',
      'Embakasi South',
      'Embakasi Central',
      'Embakasi East',
      'Embakasi West',
    ],
  },

  {
    name: 'Mombasa',
    sub_counties: ['Changamwe', 'Jomvu', 'Kisauni', 'Nyali', 'Likoni', 'Mvita'],
  },
  {
    name: 'Kwale',
    sub_counties: ['Msambweni', 'Lunga Lunga', 'Kinango', 'Matuga'],
  },
  {
    name: 'Kilifi',
    sub_counties: [
      'Kilifi North',
      'Kilifi South',
      'Kaloleni',
      'Rabai',
      'Ganze',
      'Magarini',
      'Malindi',
    ],
  },
  {
    name: 'Tana River',
    sub_counties: ['Tana Delta', 'Tana River'],
  },
  {
    name: 'Lamu',
    sub_counties: ['Lamu East', 'Lamu West'],
  },
  {
    name: 'Taita-Taveta',
    sub_counties: ['Taita', 'Voi', 'Mwatate', 'Lungalunga'],
  },
  {
    name: 'Garissa',
    sub_counties: [
      'Garissa Township',
      'Balambala',
      'Lagdera',
      'Dadaab',
      'Fafi',
    ],
  },
  {
    name: 'Wajir',
    sub_counties: [
      'Wajir North',
      'Wajir East',
      'Tarbaj',
      'Wajir West',
      'Eldas',
      'Wajir South',
    ],
  },
  {
    name: 'Mandera',
    sub_counties: [
      'Mandera North',
      'Mandera West',
      'Mandera East',
      'Banissa',
      'Lafey',
      'Mandera South',
    ],
  },
  {
    name: 'Marsabit',
    sub_counties: [
      'Marsabit Central',
      'Moyale',
      'North Horr',
      'Laisamis',
      'Saku',
      'Marsabit South',
    ],
  },
  {
    name: 'Isiolo',
    sub_counties: [
      'Isiolo North',
      'Isiolo South',
      'Isiolo Central',
      'Garbatulla',
    ],
  },
  {
    name: 'Meru',
    sub_counties: [
      'Igembe North',
      'Igembe South',
      'Imenti Central',
      'Imenti North',
      'Imenti South',
      'Tigania East',
      'Tigania West',
      'Buuri',
    ],
  },
  {
    name: 'Tharaka-Nithi',
    sub_counties: ['Tharaka North', 'Tharaka South', 'Maara'],
  },
  {
    name: 'Embu',
    sub_counties: ['Manyatta', 'Runyenjes', 'Mbeere North', 'Mbeere South'],
  },
  {
    name: 'Kitui',
    sub_counties: [
      'Kitui West',
      'Kitui Rural',
      'Kitui Central',
      'Kitui East',
      'Kitui South',
      'Mwingi West',
      'Mwingi Central',
      'Mwingi North',
    ],
  },
  {
    name: 'Machakos',
    sub_counties: [
      'Masinga',
      'Yatta',
      'Kangundo',
      'Matungulu',
      'Kathiani',
      'Mavoko',
      'Machakos Town',
    ],
  },
  {
    name: 'Makueni',
    sub_counties: ['Makueni', 'Kibwezi East', 'Kibwezi West', 'Mbooni'],
  },
  {
    name: 'Nyandarua',
    sub_counties: ['Kinangop', 'Kipipiri', "Ol'Kalou", 'Ol Jorok'],
  },
  {
    name: 'Nyeri',
    sub_counties: [
      'Tetu',
      'Kieni East',
      'Kieni West',
      'Mathira East',
      'Mathira West',
      'Nyeri South',
      'Nyeri Central',
      'Mukurwe-ini',
    ],
  },
  {
    name: 'Kirinyaga',
    sub_counties: ['Mwea', 'Gichugu', 'Ndia', 'Kirinyaga Central'],
  },
  {
    name: "Murang'a",
    sub_counties: [
      'Kangema',
      'Mathioya',
      'Kiharu',
      'Kigumo',
      'Maragua',
      'Gatanga',
      'Kandara',
    ],
  },
  {
    name: 'Kiambu',
    sub_counties: [
      'Githunguri',
      'Kiambaa',
      'Lari',
      'Limuru',
      'Kabete',
      'Gatundu North',
      'Gatundu South',
      'Juja',
      'Kikuyu',
      'Thika Town',
      'Ruiru',
      'Kiambu Town',
    ],
  },
  {
    name: 'Turkana',
    sub_counties: [
      'Turkana North',
      'Turkana West',
      'Turkana Central',
      'Loima',
      'Turkana South',
      'Turkana East',
    ],
  },
  {
    name: 'West Pokot',
    sub_counties: ['Kapenguria', 'Sigor', 'Kacheliba', 'Pokot South'],
  },
  {
    name: 'Samburu',
    sub_counties: ['Samburu North', 'Samburu East', 'Samburu West'],
  },
  {
    name: 'Trans-Nzoia',
    sub_counties: ['Cherangany', 'Kwanza', 'Endebess', 'Saboti', 'Kiminini'],
  },
  {
    name: 'Uasin Gishu',
    sub_counties: ['Soy', 'Turbo', 'Kapseret', 'Moiben', 'Ainabkoi'],
  },
  {
    name: 'Elgeyo-Marakwet',
    sub_counties: [
      'Marakwet East',
      'Marakwet West',
      'Keiyo North',
      'Keiyo South',
    ],
  },
  {
    name: 'Nandi',
    sub_counties: ['Tinderet', 'Aldai', 'Nandi Hills', 'Chesumei', 'Emgwen'],
  },
  {
    name: 'Baringo',
    sub_counties: [
      'Tiaty',
      'Baringo Central',
      'Baringo North',
      'Baringo South',
      'Mogotio',
      'Eldama Ravine',
    ],
  },
  {
    name: 'Laikipia',
    sub_counties: ['Laikipia West', 'Laikipia East', 'Laikipia North'],
  },
  {
    name: 'Nakuru',
    sub_counties: [
      'Nakuru Town West',
      'Nakuru Town East',
      'Njoro',
      'Rongai',
      'Bahati',
      'Gilgil',
      'Kuresoi South',
      'Kuresoi North',
      'Subukia',
      'Molo',
    ],
  },
  {
    name: 'Narok',
    sub_counties: [
      'Narok North',
      'Narok South',
      'Narok East',
      'Narok West',
      'Transmara East',
      'Transmara West',
    ],
  },
  {
    name: 'Kajiado',
    sub_counties: [
      'Kajiado Central',
      'Kajiado North',
      'Kajiado East',
      'Kajiado West',
      'Kajiado South',
    ],
  },
  {
    name: 'Kericho',
    sub_counties: [
      'Ainamoi',
      'Kipkelion East',
      'Kipkelion West',
      'Bureti',
      'Belgut',
      'Soin/Sigowet',
    ],
  },
  {
    name: 'Bomet',
    sub_counties: [
      'Bomet Central',
      'Bomet East',
      'Bomet West',
      'Chepalungu',
      'Sotik',
    ],
  },
  {
    name: 'Kakamega',
    sub_counties: [
      'Lugari',
      'Likuyani',
      'Malava',
      'Lurambi',
      'Navakholo',
      'Mumias East',
      'Mumias West',
      'Matungu',
      'Butere',
      'Khwisero',
      'Shinyalu',
      'Ikolomani',
    ],
  },
  {
    name: 'Vihiga',
    sub_counties: ['Vihiga', 'Sabatia', 'Hamisi', 'Luanda'],
  },
  {
    name: 'Bungoma',
    sub_counties: [
      'Mt. Elgon',
      'Sirisia',
      'Kabuchai',
      'Bumula',
      'Kanduyi',
      'Webuye East',
      'Webuye West',
      'Kimilili',
      'Tongaren',
    ],
  },
  {
    name: 'Busia',
    sub_counties: [
      'Tesol South',
      'Teso North',
      'Teso South',
      'Teso West',
      'Nambale',
      'Matayos',
      'Butula',
      'Bunyala',
    ],
  },
  {
    name: 'Siaya',
    sub_counties: [
      'Gem',
      'Alego Usonga',
      'Ugunja',
      'Ugenya',
      'Bondo',
      'Rarieda',
    ],
  },
  {
    name: 'Kisumu',
    sub_counties: [
      'Kisumu East',
      'Kisumu West',
      'Kisumu Central',
      'Seme',
      'Nyando',
      'Muhoroni',
    ],
  },
  {
    name: 'Homa Bay',
    sub_counties: [
      'Kasipul',
      'Kabondo',
      'Karachuonyo',
      'Rangwe',
      'Homa Bay Town',
      'Ndhiwa',
      'Suba',
    ],
  },
  {
    name: 'Migori',
    sub_counties: [
      'Rongo',
      'Awendo',
      'Suneka',
      'Nyatike',
      'Kuria West',
      'Kuria East',
      'Kuria South',
    ],
  },
  {
    name: 'Kisii',
    sub_counties: [
      'Bonchari',
      'South Mugirango',
      'Bomachoge Borabu',
      'Bomachoge Chache',
      'Kitutu Chache North',
      'Kitutu Chache South',
      'Nyaribari Masaba',
      'Nyaribari Chache',
    ],
  },
  {
    name: 'Nyamira',
    sub_counties: [
      'Kitutu Masaba',
      'West Mugirango',
      'North Mugirango',
      'Borabu',
    ],
  },
];
